Repository Dev-One-Project/ONF-server, pull requests merged in 2023-01, with the labels that each got.

#170 :zap: (scheduleTemplate): MODIFY: scheduleTemplate APIs 수정
  src/apis/scheduleCategories/scheduleCategory.resolver.ts
  src/apis/scheduleCategories/scheduleCategory.service.ts
  src/apis/scheduleTemplates/entities/scheduleTemplate.entity.ts
  src/apis/scheduleTemplates/scheduleTemplate.resolver.ts
  src/apis/scheduleTemplates/scheduleTemplate.service.ts
Labels: modify

#172 :zap: MODIFY: VacationIssue APIs 수정 #168
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: modify

#174 :zap: (logout): MODIFY: logout env variables, rolecategory entity name (#173)
  src/apis/auth/auth.resolver.ts
  src/apis/auth/auth.service.ts
  src/apis/roleCategory/dto/createRoleCategory.input.ts
  src/apis/roleCategory/entities/roleCategory.entity.ts
  src/apis/roleCategory/roleCategory.resolver.ts
  src/common/types/roleCategory.types.ts
Labels: modify

#176 :sparkles: FEATURE: vacationIssue update&delete 생성 #175
  src/apis/vacationIssues/entities/vacationIssue.entity.ts
  src/apis/vacationIssues/vacationIssues.resolver.ts
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: feature

#183 :zap: (Organization): MODIFY: update organization column
  src/apis/organization/dto/createOrganization.input.ts
  src/apis/organization/entities/organization.entity.ts
Labels: modify

#185 :sparkles: FEATURE: UpdateMany & DeleteMany vacation APIs 생성 #184
  src/apis/vacation/dto/updateVacation.input.ts
  src/apis/vacation/vacation.resolver.ts
  src/apis/vacation/vacation.service.ts
Labels: feature

#186 :zap: (workCheck): MODIFY: workCheck APIs 수정
  src/apis/auth/auth.service.ts
  src/apis/noticeBoards/entities/noticeBoard.entity.ts
  src/apis/scheduleTemplates/scheduleTemplate.service.ts
  src/apis/schedules/entities/schedule.entity.ts
  src/apis/schedules/schedule.resolver.ts
  src/apis/schedules/schedule.service.ts
  src/apis/workChecks/workCheck.resolver.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
  src/common/libraries/utils.ts
Labels: modify

#190 :sparkles: FEATURE: UpdateMany & DeleteMany vacationCategory APIs 생성 …
  src/apis/vacationCategory/dto/createVacationCategory.input.ts
  src/apis/vacationCategory/dto/updateVacationCategory.input.ts
  src/apis/vacationCategory/vacationCategory.resolver.ts
  src/apis/vacationCategory/vacationCategory.service.ts
Labels: feature

#192 :ambulance: (invitationCode): HOTFIX: invitationCode APIs 수정
  src/apis/invitationCode/invitationCode.service.ts
Labels: hotfix

#194 :sparkles: (WorkInfo): FEATURE: Add workInfo Apis(#193)
  src/apis/accounts/account.module.ts
  src/apis/accounts/account.resolver.ts
  src/apis/accounts/account.service.ts
  src/apis/auth/auth.module.ts
  src/apis/auth/auth.service.ts
  src/apis/workInfo/dto/createBasickInfo.input.ts
  src/apis/workInfo/dto/createFixedLaborRule.input.ts
  src/apis/workInfo/dto/createMaximumLaborRule.input.ts
  src/apis/workInfo/entites/workInfo.entity.ts
  src/apis/workInfo/workInfo.module.ts
  src/apis/workInfo/workInfo.resolver.ts
  src/apis/workInfo/workInfo.service.ts
  src/app.module.ts
  src/common/types/enum.range.ts
Labels: feature

#198 :ambulance: HOTFIX: fetchVacationIssue API 수정 #197
  src/apis/vacation/vacation.resolver.ts
  src/apis/vacation/vacation.service.ts
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: hotfix

#196 :ambulance: HOTFIX: fetchVacationCategories 수정 #195
  src/apis/vacationCategory/vacationCategory.resolver.ts
Labels: hotfix

#203 :ambulance: HOTFIX: vacation fetch 수정 #202
  src/apis/vacation/vacation.service.ts
Labels: hotfix

#201 :ambulance: HOTFIX: VacationCategory fetch 수정 #200
  src/apis/vacationCategory/vacationCategory.service.ts
Labels: hotfix

#206 :ambulance: (Login): HOTFIX: revise refreshToken apis(#205)
  src/apis/auth/auth.service.ts
  src/common/auth/jwt-refresh.strategy.ts
Labels: hotfix

#209 :sparkles: (member): FEATURE: Member APIs 추가
  src/apis/members/member.resolver.ts
  src/apis/members/member.service.ts
  src/apis/schedules/schedule.resolver.ts
  src/apis/schedules/schedule.service.ts
  src/common/graphql/schema.gql
  src/common/libraries/utils.ts
Labels: feature

#212 :ambulance: HOTFIX: vacationIssue fetch 수정 #208
  src/apis/vacationIssues/entities/vacationIssue.entity.ts
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: hotfix

#215 :ambulance: (member): HOTFIX: member APIs 수정
  src/apis/members/member.service.ts
Labels: hotfix

#219 :ambulance: HOTFIX: vacationIssue create 수정 #218
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: hotfix

#217 :sparkles: (WorkInfo): FEATURE: WorkInfo APIs 구현(#216)
  src/apis/accounts/account.service.ts
  src/apis/accounts/entites/account.entity.ts
  src/apis/auth/auth.service.ts
  src/apis/companies/entities/company.entity.ts
  src/apis/members/entities/member.entity.ts
  src/apis/workInfo/entites/workInfo.entity.ts
  src/apis/workInfo/workInfo.module.ts
  src/apis/workInfo/workInfo.resolver.ts
  src/apis/workInfo/workInfo.service.ts
Labels: feature

#225 :ambulance: (schedule): HOTFIX: schedule 수정
  src/apis/schedules/schedule.service.ts
Labels: hotfix

#222 :sparkles: (workCheck): FEATURE: workCheck APIs 추가
  src/apis/members/member.resolver.ts
  src/apis/schedules/schedule.resolver.ts
  src/apis/workChecks/dto/mainPageWorkCheck.output.ts
  src/apis/workChecks/workCheck.module.ts
  src/apis/workChecks/workCheck.resolver.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
Labels: feature

#226 :ambulance: HOTFIX: vacationIssue fetch 수정 #221
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: hotfix

#231 :ambulance: HOTFIX: createvacation API 수정 #230
  src/apis/vacation/vacation.resolver.ts
Labels: hotfix

#229 :sparkles: (WorkInfo): FEATURE: updateWorkInfo Api 구현 (#228)
  src/apis/workInfo/dto/createBasickInfo.input.ts
  src/apis/workInfo/dto/updateBasickInfo.input.ts
  src/apis/workInfo/dto/updateFixedLaborRule.input.ts
  src/apis/workInfo/dto/updateMaximumLaborRule.input.ts
  src/apis/workInfo/workInfo.resolver.ts
  src/apis/workInfo/workInfo.service.ts
Labels: feature

#232 :zap: (workCheck): MODIFY: workCheck APIs 로직 수정
  src/apis/members/entities/member.entity.ts
  src/apis/workChecks/workCheck.resolver.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
  src/common/libraries/utils.ts
Labels: modify

#235 :zap: (workCheck): MODIFY: workCheck APIs 수정
  src/apis/schedules/schedule.service.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
Labels: modify

#236 :ambulance: HOTFIX: createVacation API 로직추가 #234
  src/apis/vacation/dto/createVacation.input.ts
  src/apis/vacation/vacation.service.ts
Labels: hotfix

#238 :sparkles: (workCheck): FEATURE: workCheck APIs 추가
  src/apis/workChecks/workCheck.resolver.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
Labels: feature

#240 :zap: (member): MODIFY: member 수정
  src/apis/members/entities/member.entity.ts
  src/apis/workChecks/workCheck.service.ts
Labels: modify

#243 :ambulance: (workCheck): HOTFIX: workCheck 로직 수정
  src/apis/members/entities/member.entity.ts
  src/apis/schedules/schedule.service.ts
  src/apis/workChecks/workCheck.resolver.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
Labels: hotfix

#245 :zap: (workInfo): MODIFY: workInfo entity relation (#244)
  src/apis/accounts/account.resolver.ts
  src/apis/accounts/account.service.ts
  src/apis/accounts/entites/account.entity.ts
  src/apis/members/entities/member.entity.ts
  src/apis/members/member.resolver.ts
  src/apis/validationCode/entities/vaildationCode.entity.ts
  src/apis/validationCode/vaildationCode.module.ts
  src/apis/validationCode/vaildationCode.resolver.ts
  src/apis/validationCode/vaildationCode.service.ts
  src/apis/workInfo/entites/workInfo.entity.ts
  src/apis/workInfo/workInfo.resolver.ts
  src/apis/workInfo/workInfo.service.ts
  src/app.module.ts
  src/common/libraries/utils.ts
Labels: modify

#247 :ambulance: HOTFIX: fetchVacation API 수정 #246
  src/apis/members/entities/member.entity.ts
  src/apis/vacation/vacation.service.ts
  src/apis/vacationIssues/vacationIssues.resolver.ts
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: hotfix

#254 :ambulance: (schedule): HOTFIX: schedule APIs 수정
  src/apis/schedules/schedule.service.ts
Labels: hotfix

#257 :zap: MODIFY: fetchVacationIssue API 수정 #251
  src/apis/vacation/vacation.module.ts
  src/apis/vacation/vacation.service.ts
  src/apis/vacationCategory/entities/vacationCategory.entity.ts
  src/apis/vacationIssues/entities/vacationIssue.entity.ts
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: modify

#256 :sparkles: (workCheck): FEATURE: workCheck APIs 추가
  src/apis/workChecks/dto/createWorkCheck.input.ts
  src/apis/workChecks/dto/workCheck.output.ts
  src/apis/workChecks/workCheck.resolver.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
  src/common/libraries/utils.ts
Labels: feature

#261 :zap: (Account): MODIFY: changeAccount Apis 수정 #260
  src/apis/accounts/account.resolver.ts
  src/apis/validationCode/vaildationCode.resolver.ts
Labels: modify

#262 :zap: (workCheck): MODIFY: workCheck APIs 수정
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
Labels: modify

#263 :zap: MODIFY: fetchVacationIssue APIs 수정 #258
  src/apis/vacation/vacation.resolver.ts
  src/apis/vacation/vacation.service.ts
  src/apis/vacationIssues/vacationIssues.resolver.ts
  src/apis/vacationIssues/vacationIssues.service.ts
Labels: modify

#265 :zap: (workCheck): MODIFY: workCheck APIs 수정
  src/apis/noticeBoards/noticeBoard.resolver.ts
  src/apis/workChecks/dto/createWorkCheck.input.ts
  src/apis/workChecks/workCheck.resolver.ts
  src/apis/workChecks/workCheck.service.ts
  src/common/graphql/schema.gql
Labels: modify
